"""Curated ribbon corridor family for clean-room example animations."""

from __future__ import annotations

from anim.examples._clean_room_factories import make_ribbon_spec
from anim.examples._clean_room_shared import SceneSpec

FAMILY = "ribbons"

_EXPOSURE_BIAS = {
    "left": 0.08,
    "exchange": 0.06,
    "warm_white": 0.02,
    "dual_side": 0.02,
}

_FILL_BIAS = {
    "left": 0.01,
    "exchange": 0.01,
}


def _scene(
    name: str,
    description: str,
    *,
    count: int,
    spacing: float,
    cross_bias: float,
    beam_layout: str,
    base_exposure: float,
    support_fill: float,
) -> SceneSpec:
    return make_ribbon_spec(
        name,
        description,
        count=count,
        spacing=spacing,
        cross_bias=cross_bias,
        beam_layout=beam_layout,
        base_exposure=base_exposure + _EXPOSURE_BIAS.get(beam_layout, 0.0),
        support_fill=max(0.0, support_fill + _FILL_BIAS.get(beam_layout, 0.0)),
    )


def _corridors() -> list[SceneSpec]:
    return [
        _scene(
            "ribbon_hallway",
            "Two ribbons run a bright hallway under warm and white side light.",
            count=2,
            spacing=0.34,
            cross_bias=0.34,
            beam_layout="warm_white",
            base_exposure=3.18,
            support_fill=0.03,
        ),
        _scene(
            "ribbon_passage",
            "Three lanes cross a shallow passage with balanced side beams.",
            count=3,
            spacing=0.24,
            cross_bias=0.42,
            beam_layout="dual_side",
            base_exposure=3.20,
            support_fill=0.04,
        ),
        _scene(
            "ribbon_channel",
            "Four ribbons thread a narrow channel beneath a top wash.",
            count=4,
            spacing=0.20,
            cross_bias=0.28,
            beam_layout="left_top",
            base_exposure=3.28,
            support_fill=0.05,
        ),
        _scene(
            "ribbon_spine",
            "A compact pair holds a luminous spine through a single beam.",
            count=2,
            spacing=0.40,
            cross_bias=0.18,
            beam_layout="left",
            base_exposure=3.12,
            support_fill=0.02,
        ),
        _scene(
            "ribbon_canal",
            "Three lanes drift through a calm canal and meet at center light.",
            count=3,
            spacing=0.28,
            cross_bias=0.52,
            beam_layout="exchange",
            base_exposure=3.14,
            support_fill=0.03,
        ),
        _scene(
            "ribbon_runway",
            "Four ribbons open into a bright runway with a triad of beams.",
            count=4,
            spacing=0.18,
            cross_bias=0.24,
            beam_layout="triad",
            base_exposure=3.30,
            support_fill=0.05,
        ),
        _scene(
            "ribbon_lane",
            "Two ribbons stay wide apart for a simple warm-white lane.",
            count=2,
            spacing=0.30,
            cross_bias=0.60,
            beam_layout="warm_white",
            base_exposure=3.08,
            support_fill=0.03,
        ),
        _scene(
            "ribbon_traverse",
            "Five lanes traverse the room in a broad mirrored sweep.",
            count=5,
            spacing=0.16,
            cross_bias=0.26,
            beam_layout="dual_side",
            base_exposure=3.34,
            support_fill=0.06,
        ),
        _scene(
            "ribbon_axis",
            "Three ribbons settle on a centered axis beneath a side-and-top wash.",
            count=3,
            spacing=0.26,
            cross_bias=0.36,
            beam_layout="left_top",
            base_exposure=3.26,
            support_fill=0.04,
        ),
        _scene(
            "ribbon_lattice",
            "Four ribbons make a restrained lattice with warm and white light.",
            count=4,
            spacing=0.22,
            cross_bias=0.30,
            beam_layout="warm_white",
            base_exposure=3.22,
            support_fill=0.04,
        ),
    ]


def _braids() -> list[SceneSpec]:
    return [
        _scene(
            "ribbon_braid_pair",
            "A narrow pair braids through an off-center exchange beam.",
            count=2,
            spacing=0.32,
            cross_bias=0.56,
            beam_layout="exchange",
            base_exposure=3.10,
            support_fill=0.03,
        ),
        _scene(
            "ribbon_braid_triple",
            "Three ribbons braid under a warm-white side pairing.",
            count=3,
            spacing=0.24,
            cross_bias=0.48,
            beam_layout="warm_white",
            base_exposure=3.16,
            support_fill=0.04,
        ),
        _scene(
            "ribbon_braid_fold",
            "Four ribbons fold into a mirrored braid with dual side beams.",
            count=4,
            spacing=0.20,
            cross_bias=0.54,
            beam_layout="dual_side",
            base_exposure=3.18,
            support_fill=0.04,
        ),
        _scene(
            "ribbon_braid_stitch",
            "Three lanes stitch together under a soft top wash.",
            count=3,
            spacing=0.28,
            cross_bias=0.62,
            beam_layout="left_top",
            base_exposure=3.25,
            support_fill=0.05,
        ),
        _scene(
            "ribbon_braid_shear",
            "Four ribbons shear across a luminous triad of beams.",
            count=4,
            spacing=0.18,
            cross_bias=0.40,
            beam_layout="triad",
            base_exposure=3.32,
            support_fill=0.05,
        ),
        _scene(
            "ribbon_braid_turn",
            "A pair turns inward under a bright exchange crossing.",
            count=2,
            spacing=0.36,
            cross_bias=0.66,
            beam_layout="exchange",
            base_exposure=3.12,
            support_fill=0.03,
        ),
        _scene(
            "ribbon_braid_echo",
            "Five lanes echo each other through a warm-white corridor.",
            count=5,
            spacing=0.17,
            cross_bias=0.30,
            beam_layout="warm_white",
            base_exposure=3.28,
            support_fill=0.05,
        ),
        _scene(
            "ribbon_braid_tilt",
            "Three ribbons tilt toward a mirrored dual-side pairing.",
            count=3,
            spacing=0.26,
            cross_bias=0.58,
            beam_layout="dual_side",
            base_exposure=3.20,
            support_fill=0.04,
        ),
        _scene(
            "ribbon_braid_shell",
            "Four ribbons form a shallow shell under a single beam.",
            count=4,
            spacing=0.22,
            cross_bias=0.46,
            beam_layout="left",
            base_exposure=3.14,
            support_fill=0.03,
        ),
        _scene(
            "ribbon_braid_thread",
            "Two ribbons thread a narrow gap with a warm top wash.",
            count=2,
            spacing=0.38,
            cross_bias=0.50,
            beam_layout="left_top",
            base_exposure=3.24,
            support_fill=0.04,
        ),
    ]


def _exchanges() -> list[SceneSpec]:
    return [
        _scene(
            "ribbon_exchange_arc",
            "Two ribbons arc through a centered exchange of warm light.",
            count=2,
            spacing=0.34,
            cross_bias=0.60,
            beam_layout="exchange",
            base_exposure=3.08,
            support_fill=0.03,
        ),
        _scene(
            "ribbon_exchange_lift",
            "Three ribbons lift into a balanced dual-side exchange.",
            count=3,
            spacing=0.24,
            cross_bias=0.44,
            beam_layout="dual_side",
            base_exposure=3.16,
            support_fill=0.04,
        ),
        _scene(
            "ribbon_exchange_swerve",
            "Four ribbons swerve through a warm-white exchange lane.",
            count=4,
            spacing=0.20,
            cross_bias=0.32,
            beam_layout="warm_white",
            base_exposure=3.22,
            support_fill=0.04,
        ),
        _scene(
            "ribbon_exchange_offset",
            "Three ribbons offset around a left-top exchange beam.",
            count=3,
            spacing=0.28,
            cross_bias=0.54,
            beam_layout="left_top",
            base_exposure=3.26,
            support_fill=0.05,
        ),
        _scene(
            "ribbon_exchange_tandem",
            "Five lanes move in tandem under a bright beam triad.",
            count=5,
            spacing=0.16,
            cross_bias=0.24,
            beam_layout="triad",
            base_exposure=3.34,
            support_fill=0.06,
        ),
        _scene(
            "ribbon_exchange_split",
            "A pair splits cleanly through a centered exchange crossing.",
            count=2,
            spacing=0.40,
            cross_bias=0.68,
            beam_layout="exchange",
            base_exposure=3.12,
            support_fill=0.03,
        ),
        _scene(
            "ribbon_exchange_return",
            "Three ribbons return along the same bright side channels.",
            count=3,
            spacing=0.26,
            cross_bias=0.46,
            beam_layout="dual_side",
            base_exposure=3.20,
            support_fill=0.04,
        ),
        _scene(
            "ribbon_exchange_glide",
            "Four ribbons glide through a warm-white exchange corridor.",
            count=4,
            spacing=0.18,
            cross_bias=0.36,
            beam_layout="warm_white",
            base_exposure=3.24,
            support_fill=0.04,
        ),
        _scene(
            "ribbon_exchange_gate",
            "Three ribbons open a gate under a narrow left beam.",
            count=3,
            spacing=0.30,
            cross_bias=0.50,
            beam_layout="left",
            base_exposure=3.18,
            support_fill=0.04,
        ),
        _scene(
            "ribbon_exchange_cross",
            "Four ribbons cross at center under a bright exchange pair.",
            count=4,
            spacing=0.22,
            cross_bias=0.58,
            beam_layout="exchange",
            base_exposure=3.10,
            support_fill=0.03,
        ),
    ]


def _bridges() -> list[SceneSpec]:
    return [
        _scene(
            "ribbon_bridge_span",
            "Three ribbons span the room beneath a side and top wash.",
            count=3,
            spacing=0.24,
            cross_bias=0.34,
            beam_layout="left_top",
            base_exposure=3.24,
            support_fill=0.04,
        ),
        _scene(
            "ribbon_bridge_arch",
            "Four ribbons arch through warm-white mirrored walls.",
            count=4,
            spacing=0.20,
            cross_bias=0.28,
            beam_layout="warm_white",
            base_exposure=3.22,
            support_fill=0.04,
        ),
        _scene(
            "ribbon_bridge_step",
            "Three ribbons step across a bright triad-lit bridge.",
            count=3,
            spacing=0.26,
            cross_bias=0.40,
            beam_layout="triad",
            base_exposure=3.30,
            support_fill=0.05,
        ),
        _scene(
            "ribbon_bridge_riser",
            "A pair rises into a clear left-top bridge crossing.",
            count=2,
            spacing=0.32,
            cross_bias=0.52,
            beam_layout="left_top",
            base_exposure=3.18,
            support_fill=0.03,
        ),
        _scene(
            "ribbon_bridge_sheen",
            "Four ribbons catch a mirrored sheen from both side walls.",
            count=4,
            spacing=0.18,
            cross_bias=0.24,
            beam_layout="dual_side",
            base_exposure=3.26,
            support_fill=0.04,
        ),
        _scene(
            "ribbon_bridge_sway",
            "Three ribbons sway under a warm-white bridge light.",
            count=3,
            spacing=0.28,
            cross_bias=0.46,
            beam_layout="warm_white",
            base_exposure=3.20,
            support_fill=0.04,
        ),
        _scene(
            "ribbon_bridge_fold",
            "Five ribbons fold into a bright bridge lattice.",
            count=5,
            spacing=0.16,
            cross_bias=0.22,
            beam_layout="triad",
            base_exposure=3.34,
            support_fill=0.06,
        ),
        _scene(
            "ribbon_bridge_knot",
            "A pair knots itself under a compact exchange beam.",
            count=2,
            spacing=0.36,
            cross_bias=0.62,
            beam_layout="exchange",
            base_exposure=3.12,
            support_fill=0.03,
        ),
        _scene(
            "ribbon_bridge_pier",
            "Four ribbons anchor a bridge pier with a single side beam.",
            count=4,
            spacing=0.20,
            cross_bias=0.30,
            beam_layout="left",
            base_exposure=3.16,
            support_fill=0.03,
        ),
        _scene(
            "ribbon_bridge_crest",
            "Three ribbons crest into a luminous warm-white arch.",
            count=3,
            spacing=0.24,
            cross_bias=0.50,
            beam_layout="warm_white",
            base_exposure=3.28,
            support_fill=0.04,
        ),
    ]


def _lanterns() -> list[SceneSpec]:
    return [
        _scene(
            "ribbon_lantern_box",
            "Three ribbons frame a boxy lantern of warm and white light.",
            count=3,
            spacing=0.26,
            cross_bias=0.32,
            beam_layout="triad",
            base_exposure=3.30,
            support_fill=0.05,
        ),
        _scene(
            "ribbon_lantern_rim",
            "Four ribbons hold a bright rim under mirrored side beams.",
            count=4,
            spacing=0.18,
            cross_bias=0.26,
            beam_layout="dual_side",
            base_exposure=3.22,
            support_fill=0.04,
        ),
        _scene(
            "ribbon_lantern_slot",
            "A narrow pair slots into a clean left-top lantern opening.",
            count=2,
            spacing=0.34,
            cross_bias=0.58,
            beam_layout="left_top",
            base_exposure=3.18,
            support_fill=0.03,
        ),
        _scene(
            "ribbon_lantern_cage",
            "Five ribbons form a cage lit by warm-white walls.",
            count=5,
            spacing=0.16,
            cross_bias=0.24,
            beam_layout="warm_white",
            base_exposure=3.34,
            support_fill=0.05,
        ),
        _scene(
            "ribbon_lantern_bay",
            "Three ribbons settle into a bay lit from the left.",
            count=3,
            spacing=0.28,
            cross_bias=0.42,
            beam_layout="left",
            base_exposure=3.16,
            support_fill=0.03,
        ),
        _scene(
            "ribbon_lantern_frame",
            "Four ribbons trace a frame under a bright triad wash.",
            count=4,
            spacing=0.20,
            cross_bias=0.30,
            beam_layout="triad",
            base_exposure=3.28,
            support_fill=0.04,
        ),
        _scene(
            "ribbon_lantern_hold",
            "Two ribbons hold a compact lantern around an exchange beam.",
            count=2,
            spacing=0.38,
            cross_bias=0.64,
            beam_layout="exchange",
            base_exposure=3.10,
            support_fill=0.03,
        ),
        _scene(
            "ribbon_lantern_glow",
            "Three ribbons glow evenly under a warm-white corridor light.",
            count=3,
            spacing=0.24,
            cross_bias=0.36,
            beam_layout="warm_white",
            base_exposure=3.24,
            support_fill=0.04,
        ),
        _scene(
            "ribbon_lantern_niche",
            "Four ribbons sit in a shallow niche with a left-top wash.",
            count=4,
            spacing=0.22,
            cross_bias=0.46,
            beam_layout="left_top",
            base_exposure=3.20,
            support_fill=0.04,
        ),
        _scene(
            "ribbon_lantern_core",
            "Five ribbons keep a luminous core under a dual-side pair.",
            count=5,
            spacing=0.18,
            cross_bias=0.28,
            beam_layout="dual_side",
            base_exposure=3.32,
            support_fill=0.05,
        ),
    ]


def _weaves() -> list[SceneSpec]:
    return [
        _scene(
            "ribbon_weave_tight",
            "Four ribbons weave tightly through warm-white crossings.",
            count=4,
            spacing=0.18,
            cross_bias=0.52,
            beam_layout="warm_white",
            base_exposure=3.24,
            support_fill=0.04,
        ),
        _scene(
            "ribbon_weave_loose",
            "Three ribbons weave loosely under a balanced side pair.",
            count=3,
            spacing=0.28,
            cross_bias=0.26,
            beam_layout="dual_side",
            base_exposure=3.18,
            support_fill=0.04,
        ),
        _scene(
            "ribbon_weave_pulse",
            "Five ribbons pulse through a bright triad-lit weave.",
            count=5,
            spacing=0.16,
            cross_bias=0.30,
            beam_layout="triad",
            base_exposure=3.34,
            support_fill=0.06,
        ),
        _scene(
            "ribbon_weave_bend",
            "Three ribbons bend under a clean left-top wash.",
            count=3,
            spacing=0.24,
            cross_bias=0.48,
            beam_layout="left_top",
            base_exposure=3.22,
            support_fill=0.04,
        ),
        _scene(
            "ribbon_weave_shift",
            "Four ribbons shift in an off-center exchange lane.",
            count=4,
            spacing=0.20,
            cross_bias=0.34,
            beam_layout="exchange",
            base_exposure=3.16,
            support_fill=0.03,
        ),
        _scene(
            "ribbon_weave_stack",
            "A pair stacks into a simple beam-led ribbon column.",
            count=2,
            spacing=0.40,
            cross_bias=0.60,
            beam_layout="left",
            base_exposure=3.10,
            support_fill=0.03,
        ),
        _scene(
            "ribbon_weave_curl",
            "Three ribbons curl through a bright warm-white weave.",
            count=3,
            spacing=0.26,
            cross_bias=0.56,
            beam_layout="warm_white",
            base_exposure=3.20,
            support_fill=0.04,
        ),
        _scene(
            "ribbon_weave_gate",
            "Four ribbons gate a mirrored corridor with a top wash.",
            count=4,
            spacing=0.22,
            cross_bias=0.28,
            beam_layout="left_top",
            base_exposure=3.26,
            support_fill=0.05,
        ),
        _scene(
            "ribbon_weave_mesh",
            "Five ribbons form a bright mesh under dual side beams.",
            count=5,
            spacing=0.14,
            cross_bias=0.24,
            beam_layout="dual_side",
            base_exposure=3.36,
            support_fill=0.06,
        ),
        _scene(
            "ribbon_weave_draw",
            "Two ribbons draw clean lines through an exchange crossing.",
            count=2,
            spacing=0.30,
            cross_bias=0.50,
            beam_layout="exchange",
            base_exposure=3.12,
            support_fill=0.03,
        ),
    ]


def _gates() -> list[SceneSpec]:
    return [
        _scene(
            "ribbon_gate_open",
            "A pair opens a bright gate under dual-side light.",
            count=2,
            spacing=0.38,
            cross_bias=0.40,
            beam_layout="dual_side",
            base_exposure=3.14,
            support_fill=0.03,
        ),
        _scene(
            "ribbon_gate_narrow",
            "Three ribbons narrow into a left-top gate crossing.",
            count=3,
            spacing=0.24,
            cross_bias=0.60,
            beam_layout="left_top",
            base_exposure=3.22,
            support_fill=0.04,
        ),
        _scene(
            "ribbon_gate_wide",
            "Four ribbons widen into a bright triad-lit gate.",
            count=4,
            spacing=0.18,
            cross_bias=0.24,
            beam_layout="triad",
            base_exposure=3.30,
            support_fill=0.05,
        ),
        _scene(
            "ribbon_gate_shear",
            "Three ribbons shear under a warm-white gate beam.",
            count=3,
            spacing=0.26,
            cross_bias=0.44,
            beam_layout="warm_white",
            base_exposure=3.18,
            support_fill=0.04,
        ),
        _scene(
            "ribbon_gate_swing",
            "Five ribbons swing through a roomy dual-side gate.",
            count=5,
            spacing=0.16,
            cross_bias=0.30,
            beam_layout="dual_side",
            base_exposure=3.34,
            support_fill=0.06,
        ),
        _scene(
            "ribbon_gate_cleft",
            "A pair clefts a central opening with an exchange beam.",
            count=2,
            spacing=0.34,
            cross_bias=0.66,
            beam_layout="exchange",
            base_exposure=3.12,
            support_fill=0.03,
        ),
        _scene(
            "ribbon_gate_arc",
            "Four ribbons arc through a narrow left-lit gate.",
            count=4,
            spacing=0.20,
            cross_bias=0.38,
            beam_layout="left",
            base_exposure=3.20,
            support_fill=0.04,
        ),
        _scene(
            "ribbon_gate_hold",
            "Three ribbons hold still under a top-and-side wash.",
            count=3,
            spacing=0.28,
            cross_bias=0.52,
            beam_layout="left_top",
            base_exposure=3.24,
            support_fill=0.04,
        ),
        _scene(
            "ribbon_gate_tower",
            "Four ribbons stack into a tall gate with triad beams.",
            count=4,
            spacing=0.22,
            cross_bias=0.28,
            beam_layout="triad",
            base_exposure=3.28,
            support_fill=0.05,
        ),
        _scene(
            "ribbon_gate_cross",
            "Two ribbons cross a bright gate in a compact exchange.",
            count=2,
            spacing=0.36,
            cross_bias=0.58,
            beam_layout="exchange",
            base_exposure=3.10,
            support_fill=0.03,
        ),
    ]


SCENES = (
    _corridors()
    + _braids()
    + _exchanges()
    + _bridges()
    + _lanterns()
    + _weaves()
    + _gates()
)
