"""Curated rotor-focused clean-room scenes."""

from __future__ import annotations

from anim.examples._clean_room_factories import make_rotor_spec

FAMILY = "rotors"

CENTER = [(0.0, 0.0)]
PAIR = [(-0.58, 0.0), (0.58, 0.0)]
STACK = [(-0.54, -0.18), (0.54, 0.18)]
TRIAD = [(-0.58, -0.16), (0.0, 0.14), (0.58, -0.16)]
QUAD = [(-0.48, 0.34), (0.48, 0.34), (0.48, -0.34), (-0.48, -0.34)]
CROSS = [(-0.44, 0.0), (0.44, 0.0), (0.0, -0.28), (0.0, 0.28)]
OFFSET = [(-0.72, -0.14), (0.0, 0.0), (0.7, 0.18)]
RAIL = [(-0.8, 0.0), (0.8, 0.0)]
TRIPLE = [(-0.62, -0.2), (0.0, 0.0), (0.62, 0.22)]
DIAGONAL = [(-0.68, -0.26), (0.0, 0.0), (0.68, 0.26)]


def _spec(name: str, description: str, defaults: dict[str, object], /, **overrides: object):
    params = dict(defaults)
    params.update(overrides)
    return make_rotor_spec(name, description, **params)


COMPASS_LENS = dict(
    pivots=CENTER,
    blade_count=6,
    blade_length=0.6,
    spread=0.0,
    radial=True,
    beam_layout="triad",
    base_exposure=3.32,
    hub_kind="lens",
    spin_rate=0.14,
    support_fill=0.04,
)
COMPASS_BRIGHT = dict(
    pivots=CENTER,
    blade_count=8,
    blade_length=0.56,
    spread=0.0,
    radial=True,
    beam_layout="warm_white",
    base_exposure=3.42,
    hub_kind="lens",
    spin_rate=0.16,
    support_fill=0.05,
)
SHUTTER_WIDE = dict(
    pivots=PAIR,
    blade_count=5,
    blade_length=0.72,
    spread=1.06,
    radial=False,
    beam_layout="warm_white",
    base_exposure=3.18,
    hub_kind="prism",
    spin_rate=0.18,
    support_fill=0.03,
)
SHUTTER_TRIAD = dict(
    pivots=TRIPLE,
    blade_count=6,
    blade_length=0.68,
    spread=1.14,
    radial=False,
    beam_layout="triad",
    base_exposure=3.26,
    hub_kind="prism",
    spin_rate=0.17,
    support_fill=0.05,
)
FAN_PAIR = dict(
    pivots=PAIR,
    blade_count=7,
    blade_length=0.76,
    spread=0.92,
    radial=False,
    beam_layout="dual_side",
    base_exposure=3.22,
    hub_kind="prism",
    spin_rate=0.19,
    support_fill=0.04,
)
FAN_WARM = dict(
    pivots=STACK,
    blade_count=5,
    blade_length=0.64,
    spread=0.84,
    radial=False,
    beam_layout="warm_white",
    base_exposure=3.2,
    hub_kind="prism",
    spin_rate=0.2,
    support_fill=0.03,
)
IRIS_LENS = dict(
    pivots=CENTER,
    blade_count=8,
    blade_length=0.58,
    spread=0.0,
    radial=True,
    beam_layout="triad",
    base_exposure=3.38,
    hub_kind="lens",
    spin_rate=0.13,
    support_fill=0.05,
)
AXIS_MIX = dict(
    pivots=CROSS,
    blade_count=4,
    blade_length=0.62,
    spread=0.0,
    radial=True,
    beam_layout="dual_side",
    base_exposure=3.3,
    hub_kind="lens",
    spin_rate=0.15,
    support_fill=0.04,
)
ROTOR_PAIR = dict(
    pivots=PAIR,
    blade_count=5,
    blade_length=0.66,
    spread=1.0,
    radial=False,
    beam_layout="exchange",
    base_exposure=3.15,
    hub_kind="prism",
    spin_rate=0.18,
    support_fill=0.03,
)
ROTOR_TRIPLE = dict(
    pivots=TRIPLE,
    blade_count=4,
    blade_length=0.58,
    spread=1.1,
    radial=False,
    beam_layout="trident",
    base_exposure=3.24,
    hub_kind="prism",
    spin_rate=0.2,
    support_fill=0.04,
)


SCENES = [
    # Compass and iris forms
    _spec(
        "rotor_compass_iris",
        "An iris compass opens under warm-white beams.",
        COMPASS_BRIGHT,
    ),
    _spec(
        "rotor_compass_star",
        "A six-point compass turns through a bright side wash.",
        COMPASS_LENS,
        blade_count=6,
        blade_length=0.62,
        beam_layout="warm_white",
        base_exposure=3.26,
    ),
    _spec(
        "rotor_compass_gate",
        "A four-blade compass gate breathes around a soft core.",
        COMPASS_LENS,
        blade_count=4,
        blade_length=0.74,
        beam_layout="left_top",
        base_exposure=3.18,
    ),
    _spec(
        "rotor_compass_split",
        "Twin compass hubs hold a narrow center gap.",
        COMPASS_BRIGHT,
        pivots=PAIR,
        blade_count=4,
        blade_length=0.5,
        beam_layout="dual_side",
        base_exposure=3.22,
        support_fill=0.03,
    ),
    _spec(
        "rotor_compass_crown",
        "A three-point crown opens above a lens core.",
        COMPASS_LENS,
        pivots=TRIAD,
        blade_count=6,
        blade_length=0.58,
        beam_layout="triad",
        base_exposure=3.34,
    ),
    _spec(
        "rotor_compass_fork",
        "Forked blades catch a warm beam from the side.",
        SHUTTER_WIDE,
        pivots=OFFSET,
        blade_count=5,
        blade_length=0.64,
        beam_layout="warm_white",
        base_exposure=3.12,
    ),
    _spec(
        "rotor_compass_radar",
        "A radar compass keeps a steady, readable sweep.",
        COMPASS_LENS,
        blade_count=6,
        blade_length=0.6,
        beam_layout="dual_side",
        base_exposure=3.3,
    ),
    _spec(
        "rotor_compass_latch",
        "A latch-like compass alternates two bright phases.",
        SHUTTER_WIDE,
        pivots=PAIR,
        blade_count=5,
        blade_length=0.68,
        beam_layout="warm_white",
        base_exposure=3.24,
    ),
    _spec(
        "rotor_compass_quadrant",
        "Four quadrants turn in a clean mirrored square.",
        COMPASS_BRIGHT,
        pivots=CROSS,
        blade_count=4,
        blade_length=0.62,
        beam_layout="triad",
        base_exposure=3.38,
    ),
    _spec(
        "rotor_compass_bloom",
        "A bloom of spokes stays open and bright.",
        COMPASS_BRIGHT,
        blade_count=8,
        blade_length=0.54,
        beam_layout="warm_white",
        base_exposure=3.44,
    ),
    # Shutters and fans
    _spec(
        "rotor_shutter_gate",
        "A shutter gate opens on a warm top beam.",
        SHUTTER_TRIAD,
        pivots=PAIR,
        blade_count=6,
        blade_length=0.76,
        beam_layout="left_top",
        base_exposure=3.18,
    ),
    _spec(
        "rotor_shutter_stack",
        "Stacked blades stagger across a bright side wash.",
        SHUTTER_WIDE,
        pivots=STACK,
        blade_count=5,
        blade_length=0.72,
        beam_layout="dual_side",
        base_exposure=3.22,
    ),
    _spec(
        "rotor_shutter_fan",
        "A broad shutter fan keeps a clean diagonal flow.",
        SHUTTER_WIDE,
        blade_count=7,
        blade_length=0.8,
        beam_layout="warm_white",
        base_exposure=3.2,
    ),
    _spec(
        "rotor_shutter_lift",
        "Lifted slats expose a narrow center corridor.",
        SHUTTER_TRIAD,
        pivots=OFFSET,
        blade_count=5,
        blade_length=0.68,
        beam_layout="triad",
        base_exposure=3.3,
    ),
    _spec(
        "rotor_shutter_rib",
        "Ribbed shutters swing through a soft triad.",
        SHUTTER_TRIAD,
        pivots=RAIL,
        blade_count=6,
        blade_length=0.7,
        beam_layout="triad",
        base_exposure=3.26,
    ),
    _spec(
        "rotor_shutter_sweep",
        "Long blades sweep a bright mirrored field.",
        SHUTTER_WIDE,
        pivots=PAIR,
        blade_count=4,
        blade_length=0.86,
        beam_layout="dual_side",
        base_exposure=3.14,
    ),
    _spec(
        "rotor_shutter_clasp",
        "A clasp of shutters locks onto a white beam.",
        SHUTTER_TRIAD,
        pivots=CROSS,
        blade_count=5,
        blade_length=0.56,
        beam_layout="exchange",
        base_exposure=3.28,
    ),
    _spec(
        "rotor_shutter_fold",
        "Folded blades open like a slow mechanical petal.",
        IRIS_LENS,
        blade_count=8,
        blade_length=0.5,
        beam_layout="left_top",
        base_exposure=3.36,
    ),
    _spec(
        "rotor_shutter_baffle",
        "Baffles filter the room without losing clarity.",
        SHUTTER_WIDE,
        pivots=TRIPLE,
        blade_count=5,
        blade_length=0.74,
        beam_layout="warm_white",
        base_exposure=3.22,
    ),
    _spec(
        "rotor_shutter_tilt",
        "Tilted shutters trade symmetry for a cleaner view.",
        SHUTTER_WIDE,
        pivots=PAIR,
        blade_count=6,
        blade_length=0.66,
        beam_layout="warm_white",
        base_exposure=3.24,
    ),
    # Pair and cascade rotors
    _spec(
        "rotor_dual_axis",
        "Two rotors counter-rotate across the center line.",
        ROTOR_PAIR,
    ),
    _spec(
        "rotor_triplet_axis",
        "Three staggered rotors climb across the room.",
        ROTOR_TRIPLE,
        blade_count=5,
        blade_length=0.56,
        beam_layout="warm_white",
        base_exposure=3.24,
    ),
    _spec(
        "rotor_cascade_axis",
        "A small rotor cascade keeps each blade legible.",
        ROTOR_PAIR,
        pivots=OFFSET,
        blade_count=4,
        blade_length=0.48,
        beam_layout="exchange",
        base_exposure=3.12,
    ),
    _spec(
        "rotor_bridge_axis",
        "Paired rotors bridge a narrow mirrored gap.",
        ROTOR_PAIR,
        blade_count=6,
        blade_length=0.6,
        beam_layout="dual_side",
        base_exposure=3.28,
    ),
    _spec(
        "rotor_offset_axis",
        "Offset hubs keep the motion asymmetrical but clear.",
        ROTOR_PAIR,
        pivots=OFFSET,
        blade_count=5,
        blade_length=0.72,
        beam_layout="left_top",
        base_exposure=3.2,
    ),
    _spec(
        "rotor_ladder_axis",
        "Rotor rungs step diagonally through the room.",
        ROTOR_PAIR,
        pivots=RAIL,
        blade_count=4,
        blade_length=0.58,
        beam_layout="triad",
        base_exposure=3.18,
    ),
    _spec(
        "rotor_hinge_axis",
        "A hinged pair opens and closes in place.",
        ROTOR_PAIR,
        blade_count=6,
        blade_length=0.54,
        beam_layout="warm_white",
        base_exposure=3.34,
    ),
    _spec(
        "rotor_echo_axis",
        "Echo rotors repeat the main sweep with restraint.",
        ROTOR_TRIPLE,
        blade_count=5,
        blade_length=0.62,
        beam_layout="warm_white",
        base_exposure=3.22,
    ),
    _spec(
        "rotor_rail_axis",
        "Rail-mounted blades keep the centerline bright.",
        ROTOR_TRIPLE,
        pivots=RAIL,
        blade_count=7,
        blade_length=0.7,
        beam_layout="left_top",
        base_exposure=3.26,
    ),
    _spec(
        "rotor_anchor_axis",
        "Anchored rotors hold the room composition steady.",
        ROTOR_TRIPLE,
        blade_count=4,
        blade_length=0.78,
        beam_layout="trident",
        base_exposure=3.3,
    ),
    # Fans and drift
    _spec(
        "rotor_fan_left",
        "A left-wall fan throws clean slats across the room.",
        FAN_WARM,
        pivots=[(-0.76, 0.0)],
        blade_count=6,
        blade_length=0.84,
        beam_layout="dual_side",
        base_exposure=3.18,
    ),
    _spec(
        "rotor_fan_right",
        "A right-wall fan mirrors the same sweep in reverse.",
        FAN_WARM,
        pivots=[(0.76, 0.0)],
        blade_count=6,
        blade_length=0.84,
        beam_layout="dual_side",
        base_exposure=3.18,
    ),
    _spec(
        "rotor_fan_pair",
        "Twin fans cross in a bright warm-white exchange.",
        FAN_PAIR,
        blade_count=6,
        blade_length=0.74,
        beam_layout="dual_side",
        base_exposure=3.22,
    ),
    _spec(
        "rotor_fan_cross",
        "Crossing fans keep the center readable.",
        FAN_PAIR,
        pivots=CROSS,
        blade_count=5,
        blade_length=0.58,
        beam_layout="triad",
        base_exposure=3.24,
    ),
    _spec(
        "rotor_fan_braid",
        "Braided fans interleave without crowding the frame.",
        FAN_PAIR,
        blade_count=7,
        blade_length=0.68,
        beam_layout="exchange",
        base_exposure=3.2,
    ),
    _spec(
        "rotor_fan_halo",
        "A halo fan wraps the room with even motion.",
        FAN_WARM,
        pivots=CENTER,
        blade_count=7,
        blade_length=0.6,
        beam_layout="warm_white",
        base_exposure=3.28,
    ),
    _spec(
        "rotor_fan_lane",
        "A lane of fan blades stays bright and direct.",
        FAN_WARM,
        pivots=OFFSET,
        blade_count=5,
        blade_length=0.76,
        beam_layout="left_top",
        base_exposure=3.18,
    ),
    _spec(
        "rotor_fan_arc",
        "Arc fans lean into the beam instead of blocking it.",
        FAN_WARM,
        pivots=STACK,
        blade_count=6,
        blade_length=0.7,
        beam_layout="triad",
        base_exposure=3.26,
    ),
    _spec(
        "rotor_fan_plate",
        "Flat fan plates hold a crisp mirrored edge.",
        FAN_PAIR,
        pivots=PAIR,
        blade_count=4,
        blade_length=0.88,
        beam_layout="warm_white",
        base_exposure=3.14,
    ),
    _spec(
        "rotor_fan_drift",
        "Drifting fans trade symmetry for softer spacing.",
        FAN_PAIR,
        pivots=CROSS,
        blade_count=5,
        blade_length=0.62,
        beam_layout="dual_side",
        base_exposure=3.22,
    ),
    # Iris focus
    _spec(
        "rotor_iris_open",
        "A bright iris opens with a clean center lens.",
        IRIS_LENS,
        blade_count=8,
        blade_length=0.54,
        beam_layout="triad",
        base_exposure=3.4,
    ),
    _spec(
        "rotor_iris_close",
        "A closing iris keeps a narrow luminous seam.",
        IRIS_LENS,
        blade_count=8,
        blade_length=0.5,
        beam_layout="warm_white",
        base_exposure=3.36,
    ),
    _spec(
        "rotor_iris_ring",
        "Ring blades orbit a soft core without clutter.",
        IRIS_LENS,
        blade_count=6,
        blade_length=0.6,
        beam_layout="dual_side",
        base_exposure=3.3,
    ),
    _spec(
        "rotor_iris_split",
        "Split iris leaves a clear central channel.",
        IRIS_LENS,
        pivots=PAIR,
        blade_count=6,
        blade_length=0.58,
        beam_layout="left_top",
        base_exposure=3.32,
    ),
    _spec(
        "rotor_iris_column",
        "A vertical iris column reads clearly in profile.",
        IRIS_LENS,
        pivots=STACK,
        blade_count=5,
        blade_length=0.66,
        beam_layout="triad",
        base_exposure=3.34,
    ),
    _spec(
        "rotor_iris_helix",
        "Helical blades turn gently around the center.",
        IRIS_LENS,
        blade_count=6,
        blade_length=0.62,
        beam_layout="warm_white",
        base_exposure=3.3,
    ),
    _spec(
        "rotor_iris_diagonal",
        "Diagonal iris blades keep the motion legible.",
        IRIS_LENS,
        pivots=DIAGONAL,
        blade_count=4,
        blade_length=0.7,
        beam_layout="left_top",
        base_exposure=3.28,
    ),
    _spec(
        "rotor_iris_window",
        "Windowed blades reveal a bright inner beam.",
        IRIS_LENS,
        pivots=PAIR,
        blade_count=5,
        blade_length=0.74,
        beam_layout="exchange",
        base_exposure=3.3,
    ),
    _spec(
        "rotor_iris_nest",
        "Nested iris rings stay bright and compact.",
        IRIS_LENS,
        blade_count=8,
        blade_length=0.48,
        beam_layout="dual_side",
        base_exposure=3.42,
    ),
    _spec(
        "rotor_iris_twist",
        "A twisted iris leans the sweep just enough.",
        IRIS_LENS,
        blade_count=7,
        blade_length=0.56,
        beam_layout="triad",
        base_exposure=3.36,
    ),
    # Axis and compass variations
    _spec(
        "rotor_axis_compass",
        "Axis blades form a clean four-way compass.",
        AXIS_MIX,
        base_exposure=3.3,
    ),
    _spec(
        "rotor_axis_quadrant",
        "Quadrant blades open toward the corners.",
        AXIS_MIX,
        base_exposure=3.26,
        beam_layout="warm_white",
    ),
    _spec(
        "rotor_axis_needle",
        "A needle rotor cuts through the beam with restraint.",
        AXIS_MIX,
        pivots=PAIR,
        blade_count=5,
        blade_length=0.82,
        beam_layout="left_top",
        base_exposure=3.22,
        hub_kind="prism",
    ),
    _spec(
        "rotor_axis_wheel",
        "A wheel rotor keeps every spoke in view.",
        COMPASS_LENS,
        blade_count=8,
        blade_length=0.56,
        beam_layout="triad",
        base_exposure=3.36,
    ),
    _spec(
        "rotor_axis_grid",
        "Grid rotors stay square and readable.",
        AXIS_MIX,
        pivots=QUAD,
        blade_count=6,
        blade_length=0.6,
        beam_layout="dual_side",
        base_exposure=3.28,
        hub_kind="prism",
    ),
    _spec(
        "rotor_axis_latch",
        "A latch of blades locks onto a bright center.",
        ROTOR_PAIR,
        pivots=PAIR,
        blade_count=5,
        blade_length=0.64,
        beam_layout="exchange",
        base_exposure=3.26,
    ),
    _spec(
        "rotor_axis_bow",
        "Bow-shaped pivots give the fan a calmer read.",
        ROTOR_PAIR,
        pivots=OFFSET,
        blade_count=6,
        blade_length=0.7,
        beam_layout="warm_white",
        base_exposure=3.2,
    ),
    _spec(
        "rotor_axis_rim",
        "A rim rotor keeps the center open.",
        COMPASS_LENS,
        pivots=CENTER,
        blade_count=7,
        blade_length=0.52,
        beam_layout="left_top",
        base_exposure=3.34,
    ),
    _spec(
        "rotor_axis_clover",
        "Clover-like blades turn in a balanced loop.",
        COMPASS_LENS,
        pivots=CROSS,
        blade_count=4,
        blade_length=0.66,
        beam_layout="triad",
        base_exposure=3.34,
    ),
    _spec(
        "rotor_axis_cross",
        "Crossed rotors hold a hard but legible symmetry.",
        AXIS_MIX,
        pivots=CROSS,
        blade_count=6,
        blade_length=0.62,
        beam_layout="dual_side",
        base_exposure=3.3,
    ),
    # Mixed closing set
    _spec(
        "rotor_exchange",
        "Two rotors exchange the spotlight across the room.",
        ROTOR_PAIR,
        blade_count=5,
        blade_length=0.72,
        beam_layout="exchange",
        base_exposure=3.16,
    ),
    _spec(
        "rotor_aurora",
        "A soft aurora of blades keeps warm and white beams separate.",
        ROTOR_TRIPLE,
        blade_count=6,
        blade_length=0.58,
        beam_layout="warm_white",
        base_exposure=3.28,
        hub_kind="lens",
    ),
    _spec(
        "rotor_lattice",
        "A lattice of rotors stays bright through the gaps.",
        ROTOR_TRIPLE,
        pivots=QUAD,
        blade_count=5,
        blade_length=0.54,
        beam_layout="triad",
        base_exposure=3.32,
    ),
    _spec(
        "rotor_trellis",
        "Trellis blades form a clean mirrored scaffold.",
        SHUTTER_TRIAD,
        pivots=OFFSET,
        blade_count=5,
        blade_length=0.68,
        beam_layout="left_top",
        base_exposure=3.24,
    ),
    _spec(
        "rotor_crown",
        "A rotor crown opens around a calm lens core.",
        COMPASS_BRIGHT,
        blade_count=8,
        blade_length=0.6,
        beam_layout="triad",
        base_exposure=3.4,
    ),
    _spec(
        "rotor_sentinel",
        "Sentinel blades hold the frame without crowding it.",
        SHUTTER_WIDE,
        blade_count=4,
        blade_length=0.84,
        beam_layout="dual_side",
        base_exposure=3.16,
    ),
    _spec(
        "rotor_pylon",
        "Pylons of blades catch a warm beam from one side.",
        SHUTTER_TRIAD,
        pivots=TRIPLE,
        blade_count=5,
        blade_length=0.74,
        beam_layout="left_top",
        base_exposure=3.22,
    ),
    _spec(
        "rotor_beacon",
        "Beacon rotors keep the light centered and bright.",
        COMPASS_BRIGHT,
        blade_count=6,
        blade_length=0.66,
        beam_layout="warm_white",
        base_exposure=3.44,
    ),
    _spec(
        "rotor_clasp",
        "A clasped fan opens just enough to show the beam.",
        FAN_PAIR,
        pivots=PAIR,
        blade_count=5,
        blade_length=0.62,
        beam_layout="triad",
        base_exposure=3.26,
    ),
    _spec(
        "rotor_quorum",
        "A quorum of blades rotates in a balanced field.",
        AXIS_MIX,
        pivots=CROSS,
        blade_count=6,
        blade_length=0.58,
        beam_layout="dual_side",
        base_exposure=3.3,
        hub_kind="lens",
    ),
]
