"""Curated truss-focused clean-room family."""

from __future__ import annotations

import math

from anim.examples._clean_room_factories import (
    make_fin_array_spec,
    make_ribbon_spec,
    make_splitter_web_spec,
)
from anim.examples._clean_room_shared import SceneSpec

FAMILY = "trusses"


def _line(count: int, y: float, *, x_span: float = 1.34) -> list[tuple[float, float]]:
    if count == 1:
        return [(0.0, y)]
    return [(-x_span * 0.5 + x_span * index / (count - 1), y) for index in range(count)]


def _grid(cols: int, rows: int, *, x_span: float, y_span: float) -> list[tuple[float, float]]:
    if cols == 1 and rows == 1:
        return [(0.0, 0.0)]
    xs = [(-x_span * 0.5 + x_span * col / max(cols - 1, 1)) for col in range(cols)]
    ys = [(-y_span * 0.5 + y_span * row / max(rows - 1, 1)) for row in range(rows)]
    return [(x, y) for y in ys for x in xs]


def _diag(
    count: int,
    *,
    start: tuple[float, float],
    stop: tuple[float, float],
) -> list[tuple[float, float]]:
    if count == 1:
        return [start]
    return [
        (
            start[0] + (stop[0] - start[0]) * index / (count - 1),
            start[1] + (stop[1] - start[1]) * index / (count - 1),
        )
        for index in range(count)
    ]


def _arch(
    count: int,
    *,
    rx: float,
    ry: float,
    start: float = 0.16 * math.pi,
    stop: float = 0.84 * math.pi,
) -> list[tuple[float, float]]:
    if count == 1:
        return [(0.0, ry)]
    return [
        (rx * math.cos(start + (stop - start) * index / (count - 1)), ry * math.sin(start + (stop - start) * index / (count - 1)))
        for index in range(count)
    ]


def _fin(
    name: str,
    description: str,
    *,
    centers: list[tuple[float, float]],
    beam_layout: str,
    base_exposure: float,
    base_angle: float = math.pi * 0.5,
    fin_length: float = 0.62,
    swing: float = 0.22,
    material_kind: str = "mixed",
    core_kind: str = "prism",
    support_fill: float = 0.03,
) -> SceneSpec:
    return make_fin_array_spec(
        name,
        description,
        centers=centers,
        beam_layout=beam_layout,
        base_exposure=base_exposure,
        base_angle=base_angle,
        fin_length=fin_length,
        swing=swing,
        material_kind=material_kind,
        core_kind=core_kind,
        support_fill=support_fill,
    )


def _splitter(
    name: str,
    description: str,
    *,
    layout: str,
    beam_layout: str,
    base_exposure: float,
    core_radius: float = 0.07,
    support_fill: float = 0.03,
) -> SceneSpec:
    return make_splitter_web_spec(
        name,
        description,
        layout=layout,
        beam_layout=beam_layout,
        base_exposure=base_exposure,
        core_radius=core_radius,
        support_fill=support_fill,
    )


def _ribbon(
    name: str,
    description: str,
    *,
    count: int,
    spacing: float,
    cross_bias: float,
    beam_layout: str,
    base_exposure: float,
    support_fill: float = 0.03,
) -> SceneSpec:
    return make_ribbon_spec(
        name,
        description,
        count=count,
        spacing=spacing,
        cross_bias=cross_bias,
        beam_layout=beam_layout,
        base_exposure=base_exposure,
        support_fill=support_fill,
    )


SCENES = [
    _fin(
        "truss_lattice_span",
        "A compact lattice span stays bright under warm-white light.",
        centers=_grid(4, 2, x_span=1.14, y_span=0.42),
        beam_layout="warm_white",
        base_exposure=3.18,
        fin_length=0.60,
        swing=0.18,
        support_fill=0.03,
    ),
    _fin(
        "truss_lattice_bay",
        "A wider lattice bay keeps the bridge path easy to read.",
        centers=_grid(5, 2, x_span=1.34, y_span=0.38),
        beam_layout="dual_side",
        base_exposure=3.16,
        fin_length=0.61,
        swing=0.20,
        support_fill=0.03,
    ),
    _fin(
        "truss_trellis_wall",
        "A trellis wall of fins opens toward a left-top support beam.",
        centers=_grid(4, 3, x_span=1.12, y_span=0.70),
        beam_layout="left_top",
        base_exposure=3.20,
        fin_length=0.58,
        swing=0.22,
        core_kind="none",
        support_fill=0.02,
    ),
    _fin(
        "truss_brace_run",
        "A straight brace run crosses the room with a clean exchange.",
        centers=_line(5, 0.0, x_span=1.42),
        beam_layout="exchange",
        base_exposure=3.12,
        base_angle=math.pi * 0.25,
        fin_length=0.64,
        swing=0.28,
        material_kind="splitter",
        core_kind="ball",
        support_fill=0.02,
    ),
    _fin(
        "truss_brace_reverse",
        "A reverse brace run mirrors the same path with warm-white light.",
        centers=_line(5, 0.0, x_span=1.42),
        beam_layout="warm_white",
        base_exposure=3.14,
        base_angle=-math.pi * 0.25,
        fin_length=0.64,
        swing=0.28,
        support_fill=0.03,
    ),
    _fin(
        "truss_overpass_frame",
        "A diagonal overpass frame keeps the structural read simple.",
        centers=_diag(5, start=(-0.76, -0.30), stop=(0.76, 0.30)),
        beam_layout="triad",
        base_exposure=3.22,
        fin_length=0.58,
        swing=0.20,
        support_fill=0.04,
    ),
    _fin(
        "truss_cantilever_pair",
        "A cantilever pair hangs from a bright left-side beam.",
        centers=_line(4, 0.24, x_span=1.20),
        beam_layout="left_top",
        base_exposure=3.08,
        base_angle=0.0,
        fin_length=0.68,
        swing=0.22,
        material_kind="splitter",
        core_kind="none",
        support_fill=0.02,
    ),
    _fin(
        "truss_viaduct_span",
        "A three-by-three viaduct grid keeps the center open and bright.",
        centers=_grid(3, 3, x_span=1.02, y_span=0.78),
        beam_layout="dual_side",
        base_exposure=3.18,
        fin_length=0.56,
        swing=0.22,
        support_fill=0.03,
    ),
    _fin(
        "truss_arched_span",
        "An arched span keeps the warm beam moving through a clear vault.",
        centers=_arch(6, rx=0.82, ry=0.32),
        beam_layout="warm_white",
        base_exposure=3.26,
        fin_length=0.62,
        swing=0.19,
        support_fill=0.03,
    ),
    _fin(
        "truss_lintel",
        "A lintel line reads like a simple structural beam path.",
        centers=_line(6, -0.08, x_span=1.36),
        beam_layout="exchange",
        base_exposure=3.10,
        base_angle=0.0,
        fin_length=0.58,
        swing=0.18,
        material_kind="splitter",
        core_kind="none",
        support_fill=0.02,
    ),
    _fin(
        "truss_purlin_bay",
        "A purlin bay stacks structure without crowding the room.",
        centers=_grid(5, 3, x_span=1.22, y_span=0.62),
        beam_layout="triad",
        base_exposure=3.28,
        fin_length=0.57,
        swing=0.21,
        support_fill=0.04,
    ),
    _fin(
        "truss_crossbrace",
        "A cross-braced span stays legible under a left-top wash.",
        centers=_diag(6, start=(-0.82, 0.36), stop=(0.82, -0.36)),
        beam_layout="left_top",
        base_exposure=3.20,
        fin_length=0.60,
        swing=0.24,
        support_fill=0.03,
    ),
    _fin(
        "truss_hatchwork",
        "A hatchwork of fins keeps the bridge rhythm restrained.",
        centers=_grid(4, 2, x_span=1.06, y_span=0.54),
        beam_layout="warm_white",
        base_exposure=3.14,
        base_angle=math.pi * 0.25,
        fin_length=0.60,
        swing=0.20,
        material_kind="splitter",
        support_fill=0.03,
    ),
    _fin(
        "truss_skybridge",
        "A skybridge line opens a clean path between both side beams.",
        centers=_line(5, 0.18, x_span=1.46),
        beam_layout="dual_side",
        base_exposure=3.24,
        base_angle=0.0,
        fin_length=0.66,
        swing=0.22,
        support_fill=0.03,
    ),
    _fin(
        "truss_rampart",
        "A rampart of fins protects a bright central beam path.",
        centers=_diag(5, start=(-0.72, -0.42), stop=(0.72, 0.10)),
        beam_layout="triad",
        base_exposure=3.30,
        fin_length=0.58,
        swing=0.26,
        support_fill=0.04,
    ),
    _fin(
        "truss_switchback",
        "A switchback arch keeps the structure airy and readable.",
        centers=_arch(5, rx=0.70, ry=0.26),
        beam_layout="exchange",
        base_exposure=3.12,
        base_angle=-math.pi * 0.25,
        fin_length=0.62,
        swing=0.22,
        material_kind="splitter",
        support_fill=0.02,
    ),
    _splitter(
        "truss_gate_overpass",
        "A gate-like overpass leaves a clear lane under warm-white light.",
        layout="corridor",
        beam_layout="warm_white",
        base_exposure=3.18,
        core_radius=0.07,
        support_fill=0.03,
    ),
    _splitter(
        "truss_threshold_web",
        "A threshold web keeps both sides in balance.",
        layout="exchange",
        beam_layout="dual_side",
        base_exposure=3.16,
        core_radius=0.07,
        support_fill=0.02,
    ),
    _splitter(
        "truss_underpass",
        "An underpass web opens the center while a top beam skims above.",
        layout="corridor",
        beam_layout="left_top",
        base_exposure=3.12,
        core_radius=0.06,
        support_fill=0.02,
    ),
    _splitter(
        "truss_causeway",
        "A causeway web stays bright with a triad of structural beams.",
        layout="triad",
        beam_layout="warm_white",
        base_exposure=3.20,
        core_radius=0.07,
        support_fill=0.03,
    ),
    _splitter(
        "truss_trestle",
        "A trestle web keeps the centerline open and low-clutter.",
        layout="trident",
        beam_layout="triad",
        base_exposure=3.10,
        core_radius=0.06,
        support_fill=0.03,
    ),
    _splitter(
        "truss_crib",
        "A crib-like frame catches a side beam without crowding the room.",
        layout="compass",
        beam_layout="left",
        base_exposure=3.14,
        core_radius=0.07,
        support_fill=0.02,
    ),
    _splitter(
        "truss_lintel_crossing",
        "A lintel crossing keeps the structural geometry crisp.",
        layout="exchange",
        beam_layout="warm_white",
        base_exposure=3.22,
        core_radius=0.06,
        support_fill=0.03,
    ),
    _splitter(
        "truss_pierwork",
        "Pierwork splitters keep the beam path narrow and legible.",
        layout="corridor",
        beam_layout="dual_side",
        base_exposure=3.11,
        core_radius=0.08,
        support_fill=0.02,
    ),
    _splitter(
        "truss_bastion",
        "A bastion web anchors the bright central path.",
        layout="trident",
        beam_layout="left_top",
        base_exposure=3.08,
        core_radius=0.08,
        support_fill=0.04,
    ),
    _splitter(
        "truss_ramp",
        "A shallow ramp keeps the crossing easy to read.",
        layout="corridor",
        beam_layout="left_top",
        base_exposure=3.19,
        core_radius=0.06,
        support_fill=0.02,
    ),
    _splitter(
        "truss_quay",
        "A quay web holds the beam corridor open on both sides.",
        layout="exchange",
        beam_layout="warm_white",
        base_exposure=3.17,
        core_radius=0.08,
        support_fill=0.03,
    ),
    _splitter(
        "truss_sluice",
        "A sluice-like gate channels the warm beam through a clean slot.",
        layout="trident",
        beam_layout="triad",
        base_exposure=3.15,
        core_radius=0.06,
        support_fill=0.03,
    ),
    _splitter(
        "truss_overbridge",
        "An overbridge web leaves a readable underbeam passage.",
        layout="compass",
        beam_layout="dual_side",
        base_exposure=3.13,
        core_radius=0.07,
        support_fill=0.02,
    ),
    _splitter(
        "truss_keelway",
        "A keelway web stays bright under a centered warm beam.",
        layout="triad",
        beam_layout="warm_white",
        base_exposure=3.24,
        core_radius=0.05,
        support_fill=0.03,
    ),
    _splitter(
        "truss_nave_grid",
        "A nave grid feels like a structural aisle in a mirror room.",
        layout="compass",
        beam_layout="top",
        base_exposure=3.10,
        core_radius=0.06,
        support_fill=0.03,
    ),
    _splitter(
        "truss_flyover",
        "A flyover web keeps the crossing path light and balanced.",
        layout="exchange",
        beam_layout="left_top",
        base_exposure=3.20,
        core_radius=0.07,
        support_fill=0.02,
    ),
    _ribbon(
        "truss_cable_run",
        "A cable run braids through a structural truss lane.",
        count=2,
        spacing=0.34,
        cross_bias=0.56,
        beam_layout="exchange",
        base_exposure=3.12,
        support_fill=0.03,
    ),
    _ribbon(
        "truss_tieback",
        "A tieback pair keeps the beam path taut and bright.",
        count=3,
        spacing=0.24,
        cross_bias=0.44,
        beam_layout="warm_white",
        base_exposure=3.16,
        support_fill=0.03,
    ),
    _ribbon(
        "truss_spanline",
        "A spanline of ribbons stays clean between both walls.",
        count=4,
        spacing=0.18,
        cross_bias=0.30,
        beam_layout="dual_side",
        base_exposure=3.22,
        support_fill=0.04,
    ),
    _ribbon(
        "truss_bridle",
        "A bridle-like ribbon pair keeps the center lane open.",
        count=2,
        spacing=0.30,
        cross_bias=0.62,
        beam_layout="left_top",
        base_exposure=3.10,
        support_fill=0.02,
    ),
    _ribbon(
        "truss_lacebridge",
        "A lace bridge of ribbons holds warm and white light in balance.",
        count=4,
        spacing=0.20,
        cross_bias=0.36,
        beam_layout="triad",
        base_exposure=3.28,
        support_fill=0.04,
    ),
    _ribbon(
        "truss_harness",
        "A harness of five ribbons keeps the structural read open.",
        count=5,
        spacing=0.16,
        cross_bias=0.24,
        beam_layout="warm_white",
        base_exposure=3.18,
        support_fill=0.03,
    ),
    _ribbon(
        "truss_overhang",
        "An overhang ribbon set leaves a clean beam corridor below.",
        count=3,
        spacing=0.28,
        cross_bias=0.50,
        beam_layout="exchange",
        base_exposure=3.14,
        support_fill=0.02,
    ),
    _ribbon(
        "truss_chainway",
        "A chainway of ribbons stays compact and easy to parse.",
        count=4,
        spacing=0.22,
        cross_bias=0.38,
        beam_layout="dual_side",
        base_exposure=3.20,
        support_fill=0.03,
    ),
    _ribbon(
        "truss_parapet",
        "A parapet ribbon pair keeps the warm beam centered.",
        count=2,
        spacing=0.32,
        cross_bias=0.60,
        beam_layout="warm_white",
        base_exposure=3.08,
        support_fill=0.02,
    ),
    _ribbon(
        "truss_lattice_ribbon",
        "A lattice ribbon stack feels like a light truss diagram.",
        count=5,
        spacing=0.18,
        cross_bias=0.28,
        beam_layout="triad",
        base_exposure=3.24,
        support_fill=0.04,
    ),
    _ribbon(
        "truss_bridge_tape",
        "A bridge of ribbons stays low and clear under side light.",
        count=4,
        spacing=0.20,
        cross_bias=0.34,
        beam_layout="left_top",
        base_exposure=3.12,
        support_fill=0.03,
    ),
    _ribbon(
        "truss_suspension",
        "A suspension ribbon stack keeps both beams in play.",
        count=3,
        spacing=0.26,
        cross_bias=0.48,
        beam_layout="exchange",
        base_exposure=3.26,
        support_fill=0.03,
    ),
    _ribbon(
        "truss_girdle",
        "A girdle of ribbons tightens the room into a clean frame.",
        count=4,
        spacing=0.24,
        cross_bias=0.30,
        beam_layout="warm_white",
        base_exposure=3.18,
        support_fill=0.03,
    ),
    _ribbon(
        "truss_stayline",
        "A stayline of ribbons stays bright under paired beams.",
        count=5,
        spacing=0.16,
        cross_bias=0.22,
        beam_layout="dual_side",
        base_exposure=3.16,
        support_fill=0.02,
    ),
    _ribbon(
        "truss_trellis_ribbon",
        "A trellis ribbon frame reads like a clean structural sketch.",
        count=3,
        spacing=0.28,
        cross_bias=0.42,
        beam_layout="left_top",
        base_exposure=3.14,
        support_fill=0.02,
    ),
    _ribbon(
        "truss_overlace",
        "An overlace of ribbons crosses a bright truss corridor.",
        count=4,
        spacing=0.18,
        cross_bias=0.52,
        beam_layout="triad",
        base_exposure=3.22,
        support_fill=0.03,
    ),
]
