"""lpt2d core C++ bindings"""

import enum
from collections.abc import Mapping, Sequence
from typing import Any

# Return type from C++ properties — always a tuple
Vec2 = tuple[float, float]
# Input type accepted by nanobind — tuples and lists both work at runtime
Vec2Like = tuple[float, float] | list[float] | Sequence[float]

class ToneMap(enum.Enum):
    none = 0

    reinhard = 1

    reinhardx = 2

    aces = 3

    log = 4

class NormalizeMode(enum.Enum):
    max = 0

    rays = 1

    fixed = 2

    off = 3

class SeedMode(enum.Enum):
    deterministic = 0

    decorrelated = 1

class ProjectorProfile(enum.Enum):
    uniform = 0

    soft = 1

    gaussian = 2

class ProjectorSource(enum.Enum):
    line = 0

    ball = 1

class PolygonJoinMode(enum.Enum):
    auto = 0

    sharp = 1

    smooth = 2

class Material:
    def __init__(
        self,
        ior: float = 1.0,
        roughness: float = 0.0,
        metallic: float = 0.0,
        transmission: float = 0.0,
        absorption: float = 0.0,
        cauchy_b: float = 0.0,
        albedo: float = 1.0,
        emission: float = 0.0,
        spectral_c0: float = 0.0,
        spectral_c1: float = 0.0,
        spectral_c2: float = 0.0,
        fill: float = 0.0,
    ) -> None: ...
    @property
    def ior(self) -> float: ...
    @ior.setter
    def ior(self, arg: float, /) -> None: ...
    @property
    def roughness(self) -> float: ...
    @roughness.setter
    def roughness(self, arg: float, /) -> None: ...
    @property
    def metallic(self) -> float: ...
    @metallic.setter
    def metallic(self, arg: float, /) -> None: ...
    @property
    def transmission(self) -> float: ...
    @transmission.setter
    def transmission(self, arg: float, /) -> None: ...
    @property
    def absorption(self) -> float: ...
    @absorption.setter
    def absorption(self, arg: float, /) -> None: ...
    @property
    def cauchy_b(self) -> float: ...
    @cauchy_b.setter
    def cauchy_b(self, arg: float, /) -> None: ...
    @property
    def albedo(self) -> float: ...
    @albedo.setter
    def albedo(self, arg: float, /) -> None: ...
    @property
    def emission(self) -> float: ...
    @emission.setter
    def emission(self, arg: float, /) -> None: ...
    @property
    def spectral_c0(self) -> float: ...
    @spectral_c0.setter
    def spectral_c0(self, arg: float, /) -> None: ...
    @property
    def spectral_c1(self) -> float: ...
    @spectral_c1.setter
    def spectral_c1(self, arg: float, /) -> None: ...
    @property
    def spectral_c2(self) -> float: ...
    @spectral_c2.setter
    def spectral_c2(self, arg: float, /) -> None: ...
    @property
    def fill(self) -> float: ...
    @fill.setter
    def fill(self, arg: float, /) -> None: ...
    def __eq__(self, arg: Material, /) -> bool: ...
    def __repr__(self) -> str: ...

def glass(ior: float = 1.5, cauchy_b: float = 0.0, absorption: float = 0.0) -> Material: ...
def mirror(reflectance: float, roughness: float = 0.0) -> Material: ...
def opaque_mirror(reflectance: float, roughness: float = 0.0) -> Material: ...
def diffuse(reflectance: float) -> Material: ...
def absorber() -> Material: ...
def emissive(emission: float, base: Material = ...) -> Material: ...
def beam_splitter(reflectance: float, roughness: float = 0.0) -> Material: ...
def named_color(name: str) -> tuple: ...
def spectral_fill_rgb(c0: float, c1: float, c2: float) -> tuple: ...
def rgb_to_spectral(r: float, g: float, b: float) -> tuple: ...
def named_color_list() -> list: ...

class Circle:
    def __init__(
        self,
        id: str = "",
        center: Vec2Like = (0.0, 0.0),
        radius: float = 0.10000000149011612,
        material: object | None = None,
        material_id: str = "",
    ) -> None: ...
    @property
    def id(self) -> str: ...
    @id.setter
    def id(self, arg: str, /) -> None: ...
    @property
    def center(self) -> Vec2: ...
    @center.setter
    def center(self, arg: Vec2Like, /) -> None: ...
    @property
    def radius(self) -> float: ...
    @radius.setter
    def radius(self, arg: float, /) -> None: ...
    @property
    def material(self) -> Material: ...
    @material.setter
    def material(self, arg: Material, /) -> None: ...
    @property
    def material_id(self) -> str: ...
    @material_id.setter
    def material_id(self, arg: str, /) -> None: ...
    def __repr__(self) -> str: ...

class Segment:
    def __init__(
        self,
        id: str = "",
        a: Vec2Like = (0.0, 0.0),
        b: Vec2Like = (0.0, 0.0),
        material: object | None = None,
        material_id: str = "",
    ) -> None: ...
    @property
    def id(self) -> str: ...
    @id.setter
    def id(self, arg: str, /) -> None: ...
    @property
    def a(self) -> Vec2: ...
    @a.setter
    def a(self, arg: Vec2Like, /) -> None: ...
    @property
    def b(self) -> Vec2: ...
    @b.setter
    def b(self, arg: Vec2Like, /) -> None: ...
    @property
    def material(self) -> Material: ...
    @material.setter
    def material(self, arg: Material, /) -> None: ...
    @property
    def material_id(self) -> str: ...
    @material_id.setter
    def material_id(self, arg: str, /) -> None: ...

class Arc:
    def __init__(
        self,
        id: str = "",
        center: Vec2Like = (0.0, 0.0),
        radius: float = 0.10000000149011612,
        angle_start: float = 0.0,
        sweep: float = 6.2831854820251465,
        material: object | None = None,
        material_id: str = "",
    ) -> None: ...
    @property
    def id(self) -> str: ...
    @id.setter
    def id(self, arg: str, /) -> None: ...
    @property
    def center(self) -> Vec2: ...
    @center.setter
    def center(self, arg: Vec2Like, /) -> None: ...
    @property
    def radius(self) -> float: ...
    @radius.setter
    def radius(self, arg: float, /) -> None: ...
    @property
    def angle_start(self) -> float: ...
    @angle_start.setter
    def angle_start(self, arg: float, /) -> None: ...
    @property
    def sweep(self) -> float: ...
    @sweep.setter
    def sweep(self, arg: float, /) -> None: ...
    @property
    def material(self) -> Material: ...
    @material.setter
    def material(self, arg: Material, /) -> None: ...
    @property
    def material_id(self) -> str: ...
    @material_id.setter
    def material_id(self, arg: str, /) -> None: ...

class Bezier:
    def __init__(
        self,
        id: str = "",
        p0: Vec2Like = (0.0, 0.0),
        p1: Vec2Like = (0.5, 0.5),
        p2: Vec2Like = (1.0, 0.0),
        material: object | None = None,
        material_id: str = "",
    ) -> None: ...
    @property
    def id(self) -> str: ...
    @id.setter
    def id(self, arg: str, /) -> None: ...
    @property
    def p0(self) -> Vec2: ...
    @p0.setter
    def p0(self, arg: Vec2Like, /) -> None: ...
    @property
    def p1(self) -> Vec2: ...
    @p1.setter
    def p1(self, arg: Vec2Like, /) -> None: ...
    @property
    def p2(self) -> Vec2: ...
    @p2.setter
    def p2(self, arg: Vec2Like, /) -> None: ...
    @property
    def material(self) -> Material: ...
    @material.setter
    def material(self, arg: Material, /) -> None: ...
    @property
    def material_id(self) -> str: ...
    @material_id.setter
    def material_id(self, arg: str, /) -> None: ...

class Polygon:
    def __init__(
        self,
        id: str = "",
        vertices: Sequence[Vec2Like] = [],
        material: object | None = None,
        material_id: str = "",
        corner_radius: float = 0.0,
        corner_radii: Sequence[float] = [],
        smooth_angle: float = 0.0,
        join_modes: Sequence[PolygonJoinMode | str] | None = None,
    ) -> None: ...
    @property
    def id(self) -> str: ...
    @id.setter
    def id(self, arg: str, /) -> None: ...
    @property
    def vertices(self) -> list[Vec2]: ...
    @vertices.setter
    def vertices(self, arg: Sequence[Vec2Like], /) -> None: ...
    @property
    def corner_radius(self) -> float: ...
    @corner_radius.setter
    def corner_radius(self, arg: float, /) -> None: ...
    @property
    def corner_radii(self) -> list[float]: ...
    @corner_radii.setter
    def corner_radii(self, arg: Sequence[float], /) -> None: ...
    @property
    def join_modes(self) -> list[PolygonJoinMode]: ...
    @join_modes.setter
    def join_modes(self, arg: Sequence[PolygonJoinMode | str] | None, /) -> None: ...
    @property
    def smooth_angle(self) -> float: ...
    @smooth_angle.setter
    def smooth_angle(self, arg: float, /) -> None: ...
    @property
    def material(self) -> Material: ...
    @material.setter
    def material(self, arg: Material, /) -> None: ...
    @property
    def material_id(self) -> str: ...
    @material_id.setter
    def material_id(self, arg: str, /) -> None: ...

class Ellipse:
    def __init__(
        self,
        id: str = "",
        center: Vec2Like = (0.0, 0.0),
        semi_a: float = 0.20000000298023224,
        semi_b: float = 0.10000000149011612,
        rotation: float = 0.0,
        material: object | None = None,
        material_id: str = "",
    ) -> None: ...
    @property
    def id(self) -> str: ...
    @id.setter
    def id(self, arg: str, /) -> None: ...
    @property
    def center(self) -> Vec2: ...
    @center.setter
    def center(self, arg: Vec2Like, /) -> None: ...
    @property
    def semi_a(self) -> float: ...
    @semi_a.setter
    def semi_a(self, arg: float, /) -> None: ...
    @property
    def semi_b(self) -> float: ...
    @semi_b.setter
    def semi_b(self, arg: float, /) -> None: ...
    @property
    def rotation(self) -> float: ...
    @rotation.setter
    def rotation(self, arg: float, /) -> None: ...
    @property
    def material(self) -> Material: ...
    @material.setter
    def material(self, arg: Material, /) -> None: ...
    @property
    def material_id(self) -> str: ...
    @material_id.setter
    def material_id(self, arg: str, /) -> None: ...

class Path:
    def __init__(
        self,
        id: str = "",
        points: Sequence[Vec2Like] = [],
        material: object | None = None,
        material_id: str = "",
        closed: bool = False,
    ) -> None: ...
    @property
    def id(self) -> str: ...
    @id.setter
    def id(self, arg: str, /) -> None: ...
    @property
    def points(self) -> list[Vec2]: ...
    @points.setter
    def points(self, arg: Sequence[Vec2Like], /) -> None: ...
    @property
    def closed(self) -> bool: ...
    @closed.setter
    def closed(self, arg: bool, /) -> None: ...
    @property
    def material(self) -> Material: ...
    @material.setter
    def material(self, arg: Material, /) -> None: ...
    @property
    def material_id(self) -> str: ...
    @material_id.setter
    def material_id(self, arg: str, /) -> None: ...

class PointLight:
    def __init__(
        self,
        id: str = "",
        position: Vec2Like = (0.0, 0.0),
        intensity: float = 1.0,
        wavelength_min: float = 380.0,
        wavelength_max: float = 780.0,
    ) -> None: ...
    @property
    def id(self) -> str: ...
    @id.setter
    def id(self, arg: str, /) -> None: ...
    @property
    def position(self) -> Vec2: ...
    @position.setter
    def position(self, arg: Vec2Like, /) -> None: ...
    @property
    def intensity(self) -> float: ...
    @intensity.setter
    def intensity(self, arg: float, /) -> None: ...
    @property
    def wavelength_min(self) -> float: ...
    @wavelength_min.setter
    def wavelength_min(self, arg: float, /) -> None: ...
    @property
    def wavelength_max(self) -> float: ...
    @wavelength_max.setter
    def wavelength_max(self, arg: float, /) -> None: ...

class SegmentLight:
    def __init__(
        self,
        id: str = "",
        a: Vec2Like = (0.0, 0.0),
        b: Vec2Like = (0.0, 0.0),
        intensity: float = 1.0,
        wavelength_min: float = 380.0,
        wavelength_max: float = 780.0,
    ) -> None: ...
    @property
    def id(self) -> str: ...
    @id.setter
    def id(self, arg: str, /) -> None: ...
    @property
    def a(self) -> Vec2: ...
    @a.setter
    def a(self, arg: Vec2Like, /) -> None: ...
    @property
    def b(self) -> Vec2: ...
    @b.setter
    def b(self, arg: Vec2Like, /) -> None: ...
    @property
    def intensity(self) -> float: ...
    @intensity.setter
    def intensity(self, arg: float, /) -> None: ...
    @property
    def wavelength_min(self) -> float: ...
    @wavelength_min.setter
    def wavelength_min(self, arg: float, /) -> None: ...
    @property
    def wavelength_max(self) -> float: ...
    @wavelength_max.setter
    def wavelength_max(self, arg: float, /) -> None: ...

class ProjectorLight:
    def __init__(
        self,
        id: str = "",
        position: Vec2Like = (0.0, 0.0),
        direction: Vec2Like = (1.0, 0.0),
        source_radius: float = 0.029999999329447746,
        spread: float = 0.10000000149011612,
        profile: object = "uniform",
        source: object = "line",
        softness: float = 0.0,
        intensity: float = 1.0,
        wavelength_min: float = 380.0,
        wavelength_max: float = 780.0,
    ) -> None: ...
    @property
    def id(self) -> str: ...
    @id.setter
    def id(self, arg: str, /) -> None: ...
    @property
    def position(self) -> Vec2: ...
    @position.setter
    def position(self, arg: Vec2Like, /) -> None: ...
    @property
    def direction(self) -> Vec2: ...
    @direction.setter
    def direction(self, arg: Vec2Like, /) -> None: ...
    @property
    def source_radius(self) -> float: ...
    @source_radius.setter
    def source_radius(self, arg: float, /) -> None: ...
    @property
    def spread(self) -> float: ...
    @spread.setter
    def spread(self, arg: float, /) -> None: ...
    @property
    def profile(self) -> str: ...
    @profile.setter
    def profile(self, arg: object, /) -> None: ...
    @property
    def source(self) -> str: ...
    @source.setter
    def source(self, arg: object, /) -> None: ...
    @property
    def softness(self) -> float: ...
    @softness.setter
    def softness(self, arg: float, /) -> None: ...
    @property
    def intensity(self) -> float: ...
    @intensity.setter
    def intensity(self, arg: float, /) -> None: ...
    @property
    def wavelength_min(self) -> float: ...
    @wavelength_min.setter
    def wavelength_min(self, arg: float, /) -> None: ...
    @property
    def wavelength_max(self) -> float: ...
    @wavelength_max.setter
    def wavelength_max(self, arg: float, /) -> None: ...

class Transform2D:
    def __init__(
        self, translate: Vec2Like = (0.0, 0.0), rotate: float = 0.0, scale: Vec2Like = (1.0, 1.0)
    ) -> None: ...
    @property
    def translate(self) -> Vec2: ...
    @translate.setter
    def translate(self, arg: Vec2Like, /) -> None: ...
    @property
    def rotate(self) -> float: ...
    @rotate.setter
    def rotate(self, arg: float, /) -> None: ...
    @property
    def scale(self) -> Vec2: ...
    @scale.setter
    def scale(self, arg: Vec2Like, /) -> None: ...

    # monkey-patched by anim.types
    @staticmethod
    def uniform(
        translate: Vec2Like = (0, 0), rotate: float = 0.0, scale: float = 1.0
    ) -> Transform2D: ...

class Group:
    def __init__(
        self,
        id: str = "",
        transform: Transform2D = ...,
        shapes: Sequence[Circle | Segment | Arc | Bezier | Polygon | Ellipse | Path] = [],
        lights: Sequence[PointLight | SegmentLight | ProjectorLight] = [],
    ) -> None: ...
    @property
    def id(self) -> str: ...
    @id.setter
    def id(self, arg: str, /) -> None: ...
    @property
    def transform(self) -> Transform2D: ...
    @transform.setter
    def transform(self, arg: Transform2D, /) -> None: ...
    @property
    def shapes(self) -> list[Circle | Segment | Arc | Bezier | Polygon | Ellipse | Path]: ...
    @shapes.setter
    def shapes(
        self, arg: Sequence[Circle | Segment | Arc | Bezier | Polygon | Ellipse | Path], /
    ) -> None: ...
    @property
    def lights(self) -> list[PointLight | SegmentLight | ProjectorLight]: ...
    @lights.setter
    def lights(self, arg: Sequence[PointLight | SegmentLight | ProjectorLight], /) -> None: ...

class Scene:
    def __init__(
        self,
        shapes: Sequence[Circle | Segment | Arc | Bezier | Polygon | Ellipse | Path] = [],
        lights: Sequence[PointLight | SegmentLight | ProjectorLight] = [],
        groups: Sequence[Group] = [],
        materials: Mapping[str, Material] = {},
    ) -> None: ...
    @property
    def shapes(self) -> list[Circle | Segment | Arc | Bezier | Polygon | Ellipse | Path]: ...
    @shapes.setter
    def shapes(
        self, arg: Sequence[Circle | Segment | Arc | Bezier | Polygon | Ellipse | Path], /
    ) -> None: ...
    @property
    def lights(self) -> list[PointLight | SegmentLight | ProjectorLight]: ...
    @lights.setter
    def lights(self, arg: Sequence[PointLight | SegmentLight | ProjectorLight], /) -> None: ...
    @property
    def groups(self) -> list[Group]: ...
    @groups.setter
    def groups(self, arg: Sequence[Group], /) -> None: ...
    @property
    def materials(self) -> dict[str, Material]: ...
    @materials.setter
    def materials(self, arg: Mapping[str, Material], /) -> None: ...

    # monkey-patched by anim.types
    def find_shape(
        self, entity_id: str
    ) -> Circle | Segment | Arc | Bezier | Polygon | Ellipse | Path | None: ...
    def find_light(self, entity_id: str) -> PointLight | SegmentLight | ProjectorLight | None: ...
    def find_group(self, entity_id: str) -> Group | None: ...
    def clone(self) -> Scene: ...
    def require_shape(
        self, entity_id: str
    ) -> Circle | Segment | Arc | Bezier | Polygon | Ellipse | Path: ...
    def require_light(self, entity_id: str) -> PointLight | SegmentLight | ProjectorLight: ...
    def require_group(self, entity_id: str) -> Group: ...
    def require_material(self, material_id: str) -> Material: ...

class Bounds:
    def __init__(self, min: Vec2Like = (0.0, 0.0), max: Vec2Like = (0.0, 0.0)) -> None: ...
    @property
    def min(self) -> Vec2: ...
    @min.setter
    def min(self, arg: Vec2Like, /) -> None: ...
    @property
    def max(self) -> Vec2: ...
    @max.setter
    def max(self, arg: Vec2Like, /) -> None: ...

class Camera2D:
    def __init__(
        self,
        bounds: object | None = None,
        center: Vec2Like | None = None,
        width: float | None = None,
    ) -> None: ...
    @property
    def bounds(self) -> Bounds | None: ...
    @bounds.setter
    def bounds(self, arg: Bounds | None) -> None: ...
    @property
    def center(self) -> Vec2 | None: ...
    @center.setter
    def center(self, arg: Vec2Like | None) -> None: ...
    @property
    def width(self) -> float | None: ...
    @width.setter
    def width(self, arg: float | None) -> None: ...
    def empty(self) -> bool: ...

class Canvas:
    def __init__(self, width: int = 1920, height: int = 1080) -> None: ...
    @property
    def width(self) -> int: ...
    @width.setter
    def width(self, arg: int, /) -> None: ...
    @property
    def height(self) -> int: ...
    @height.setter
    def height(self, arg: int, /) -> None: ...
    @property
    def aspect(self) -> float: ...

class Look:
    def __init__(
        self,
        exposure: float = -5.0,
        contrast: float = 1.0,
        gamma: float = 2.0,
        tonemap: object = "reinhardx",
        white_point: float = 0.5,
        normalize: object = "rays",
        normalize_ref: float = 0.0,
        normalize_pct: float = 1.0,
        ambient: float = 0.0,
        background: Sequence[float] = [0.0, 0.0, 0.0],
        opacity: float = 1.0,
        saturation: float = 1.0,
        vignette: float = 0.0,
        vignette_radius: float = 0.699999988079071,
        temperature: float = 0.0,
        highlights: float = 0.0,
        shadows: float = 0.0,
        hue_shift: float = 0.0,
        grain: float = 0.0,
        grain_seed: int = 0,
        chromatic_aberration: float = 0.0,
    ) -> None: ...
    @property
    def exposure(self) -> float: ...
    @exposure.setter
    def exposure(self, arg: float, /) -> None: ...
    @property
    def contrast(self) -> float: ...
    @contrast.setter
    def contrast(self, arg: float, /) -> None: ...
    @property
    def gamma(self) -> float: ...
    @gamma.setter
    def gamma(self, arg: float, /) -> None: ...
    @property
    def tonemap(self) -> str: ...
    @tonemap.setter
    def tonemap(self, arg: object, /) -> None: ...
    @property
    def white_point(self) -> float: ...
    @white_point.setter
    def white_point(self, arg: float, /) -> None: ...
    @property
    def normalize(self) -> str: ...
    @normalize.setter
    def normalize(self, arg: object, /) -> None: ...
    @property
    def normalize_ref(self) -> float: ...
    @normalize_ref.setter
    def normalize_ref(self, arg: float, /) -> None: ...
    @property
    def normalize_pct(self) -> float: ...
    @normalize_pct.setter
    def normalize_pct(self, arg: float, /) -> None: ...
    @property
    def ambient(self) -> float: ...
    @ambient.setter
    def ambient(self, arg: float, /) -> None: ...
    @property
    def background(self) -> list[float]: ...
    @background.setter
    def background(self, arg: Sequence[float], /) -> None: ...
    @property
    def opacity(self) -> float: ...
    @opacity.setter
    def opacity(self, arg: float, /) -> None: ...
    @property
    def saturation(self) -> float: ...
    @saturation.setter
    def saturation(self, arg: float, /) -> None: ...
    @property
    def vignette(self) -> float: ...
    @vignette.setter
    def vignette(self, arg: float, /) -> None: ...
    @property
    def vignette_radius(self) -> float: ...
    @vignette_radius.setter
    def vignette_radius(self, arg: float, /) -> None: ...
    @property
    def temperature(self) -> float: ...
    @temperature.setter
    def temperature(self, arg: float, /) -> None: ...
    @property
    def highlights(self) -> float: ...
    @highlights.setter
    def highlights(self, arg: float, /) -> None: ...
    @property
    def shadows(self) -> float: ...
    @shadows.setter
    def shadows(self, arg: float, /) -> None: ...
    @property
    def hue_shift(self) -> float: ...
    @hue_shift.setter
    def hue_shift(self, arg: float, /) -> None: ...
    @property
    def grain(self) -> float: ...
    @grain.setter
    def grain(self, arg: float, /) -> None: ...
    @property
    def grain_seed(self) -> int: ...
    @grain_seed.setter
    def grain_seed(self, arg: int, /) -> None: ...
    @property
    def chromatic_aberration(self) -> float: ...
    @chromatic_aberration.setter
    def chromatic_aberration(self, arg: float, /) -> None: ...
    def to_post_process(self) -> PostProcess: ...

    # monkey-patched by anim.types
    def with_overrides(self, **overrides: Any) -> Look: ...

class TraceDefaults:
    def __init__(
        self,
        rays: int = 10000000,
        batch: int = 200000,
        depth: int = 12,
        intensity: float = 1.0,
        seed_mode: object = "deterministic",
    ) -> None: ...
    @property
    def rays(self) -> int: ...
    @rays.setter
    def rays(self, arg: int, /) -> None: ...
    @property
    def batch(self) -> int: ...
    @batch.setter
    def batch(self, arg: int, /) -> None: ...
    @property
    def depth(self) -> int: ...
    @depth.setter
    def depth(self, arg: int, /) -> None: ...
    @property
    def intensity(self) -> float: ...
    @intensity.setter
    def intensity(self, arg: float, /) -> None: ...
    @property
    def seed_mode(self) -> str: ...
    @seed_mode.setter
    def seed_mode(self, arg: object, /) -> None: ...
    def to_trace_config(self, frame: int = 0) -> TraceConfig: ...

class TraceConfig:
    def __init__(self) -> None: ...
    @property
    def batch_size(self) -> int: ...
    @batch_size.setter
    def batch_size(self, arg: int, /) -> None: ...
    @property
    def depth(self) -> int: ...
    @depth.setter
    def depth(self, arg: int, /) -> None: ...
    @property
    def intensity(self) -> float: ...
    @intensity.setter
    def intensity(self, arg: float, /) -> None: ...
    @property
    def seed_mode(self) -> str: ...
    @seed_mode.setter
    def seed_mode(self, arg: object, /) -> None: ...
    @property
    def frame(self) -> int: ...
    @frame.setter
    def frame(self, arg: int, /) -> None: ...

class PostProcess:
    def __init__(self) -> None: ...
    @property
    def exposure(self) -> float: ...
    @exposure.setter
    def exposure(self, arg: float, /) -> None: ...
    @property
    def contrast(self) -> float: ...
    @contrast.setter
    def contrast(self, arg: float, /) -> None: ...
    @property
    def gamma(self) -> float: ...
    @gamma.setter
    def gamma(self, arg: float, /) -> None: ...
    @property
    def white_point(self) -> float: ...
    @white_point.setter
    def white_point(self, arg: float, /) -> None: ...
    @property
    def normalize_ref(self) -> float: ...
    @normalize_ref.setter
    def normalize_ref(self, arg: float, /) -> None: ...
    @property
    def normalize_pct(self) -> float: ...
    @normalize_pct.setter
    def normalize_pct(self, arg: float, /) -> None: ...
    @property
    def ambient(self) -> float: ...
    @ambient.setter
    def ambient(self, arg: float, /) -> None: ...
    @property
    def opacity(self) -> float: ...
    @opacity.setter
    def opacity(self, arg: float, /) -> None: ...
    @property
    def saturation(self) -> float: ...
    @saturation.setter
    def saturation(self, arg: float, /) -> None: ...
    @property
    def vignette(self) -> float: ...
    @vignette.setter
    def vignette(self, arg: float, /) -> None: ...
    @property
    def vignette_radius(self) -> float: ...
    @vignette_radius.setter
    def vignette_radius(self, arg: float, /) -> None: ...
    @property
    def temperature(self) -> float: ...
    @temperature.setter
    def temperature(self, arg: float, /) -> None: ...
    @property
    def highlights(self) -> float: ...
    @highlights.setter
    def highlights(self, arg: float, /) -> None: ...
    @property
    def shadows(self) -> float: ...
    @shadows.setter
    def shadows(self, arg: float, /) -> None: ...
    @property
    def hue_shift(self) -> float: ...
    @hue_shift.setter
    def hue_shift(self, arg: float, /) -> None: ...
    @property
    def grain(self) -> float: ...
    @grain.setter
    def grain(self, arg: float, /) -> None: ...
    @property
    def grain_seed(self) -> int: ...
    @grain_seed.setter
    def grain_seed(self, arg: int, /) -> None: ...
    @property
    def chromatic_aberration(self) -> float: ...
    @chromatic_aberration.setter
    def chromatic_aberration(self, arg: float, /) -> None: ...
    @property
    def tonemap(self) -> str: ...
    @tonemap.setter
    def tonemap(self, arg: object, /) -> None: ...
    @property
    def normalize(self) -> str: ...
    @normalize.setter
    def normalize(self, arg: object, /) -> None: ...
    @property
    def background(self) -> list[float]: ...
    @background.setter
    def background(self, arg: Sequence[float], /) -> None: ...

class Shot:
    def __init__(
        self,
        name: str = "",
        scene: Scene = ...,
        camera: Camera2D = ...,
        canvas: Canvas = ...,
        look: Look = ...,
        trace: TraceDefaults = ...,
    ) -> None: ...
    @property
    def name(self) -> str: ...
    @name.setter
    def name(self, arg: str, /) -> None: ...
    @property
    def scene(self) -> Scene: ...
    @scene.setter
    def scene(self, arg: Scene, /) -> None: ...
    @property
    def camera(self) -> Camera2D: ...
    @camera.setter
    def camera(self, arg: Camera2D, /) -> None: ...
    @property
    def canvas(self) -> Canvas: ...
    @canvas.setter
    def canvas(self, arg: Canvas, /) -> None: ...
    @property
    def look(self) -> Look: ...
    @look.setter
    def look(self, arg: Look, /) -> None: ...
    @property
    def trace(self) -> TraceDefaults: ...
    @trace.setter
    def trace(self, arg: TraceDefaults, /) -> None: ...

def load_shot(path: str) -> Shot: ...
def load_shot_json_string(json_content: str) -> Shot: ...
def save_shot(shot: Shot, path: str) -> None: ...
def resolve_material(
    shape: Circle | Segment | Arc | Bezier | Polygon | Ellipse | Path, scene: Scene
) -> Material: ...
def compute_bounds(scene: Scene, padding: float = 0.05000000074505806) -> Bounds: ...
def validate_scene(scene: Scene) -> None: ...
def normalize_scene(scene: Scene) -> None: ...
def ray_intersect(
    scene: Scene, origin: Vec2Like, direction: Vec2Like
) -> tuple[float, Vec2, Vec2, str] | None: ...
def _polygon_fill_boundary(polygon: Polygon, arc_segments: int = 8) -> list[Vec2]: ...
def _triangulate_simple_polygon(vertices: Sequence[Vec2Like]) -> list[int]: ...

class FrameMetrics:
    @property
    def mean_lum(self) -> float: ...
    @property
    def pct_black(self) -> float: ...
    @property
    def pct_clipped(self) -> float: ...
    @property
    def p50(self) -> float: ...
    @property
    def p95(self) -> float: ...
    @property
    def histogram(self) -> list[int]: ...

class RenderResult:
    @property
    def pixels(self) -> bytes: ...
    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...
    @property
    def total_rays(self) -> int: ...
    @property
    def max_hdr(self) -> float: ...
    @property
    def metrics(self) -> FrameMetrics: ...
    @property
    def time_ms(self) -> float: ...

class RenderSession:
    def __init__(self, width: int, height: int, half_float: bool = False) -> None: ...
    def close(self) -> None: ...
    def render_shot(self, shot: Shot, frame: int = 0) -> RenderResult: ...
    def render_frame(
        self, scene: Scene, bounds: Bounds, trace_cfg: TraceConfig, pp: PostProcess, total_rays: int
    ) -> RenderResult: ...
    def resize(self, width: int, height: int) -> None: ...
    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...
